apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: rca-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: rca-demo
spec:
  selector:
    app: database
  ports:
  - port: 6379
    targetPort: 6379
