apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: rca-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "32Mi"
          limits:
            cpu: "100m"
            memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: rca-demo
spec:
  selector:
    app: payment
  ports:
  - port: 80
    targetPort: 80
